name: ethereum_util
description: a collection of utility functions for Ethereum
version: 1.3.0
author: Peter Chung <touhonoob@gmail.com>
homepage: https://github.com/ethereumdart/ethereum_util

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.1.0
  convert: ^3.0.0
  quiver: '>=2.0.0 <3.0.0'
  pointycastle: ^3.0.1
  buffer: ^1.0.6
  equatable: ^2.0.3
  collection: ^1.15.0

dev_dependencies:
  path: ^1.6.2
  test: ^1.9.0
